# Introduction to Python & Jupyter Notebook

# 1_Intro_to_Python.ipynb

## Defining Variables

In [2]:
"Hello World"

'Hello World'

In [5]:
greeting = "Hello World" # this is a string variable (<- this is a comment)

In [6]:
greeting

'Hello World'

In [8]:
greeting = "Hello World"
greeting

'Hello World'

In [9]:
print(greeting)

Hello World


## Basic Math

Define two variables

In [10]:
a = 2
b = 15

Get the sum

In [11]:
a + b

17

In [12]:
my_sum = a + b # get sum of a & b

In [13]:
# print sum
my_sum

17

Get the product

In [14]:
my_product = a * b
my_product

30

## Import libraries

numpy - Numerical Python (http://numpy.org)

In [15]:
import numpy as np

Define a numpy as array

In [16]:
ages_list = [25, 30, 35, 40, 45] # this is a Python list

In [17]:
ages = np.array(ages_list) # this is a numpy array

In [18]:
ages

array([25, 30, 35, 40, 45])

In [20]:
# you can also do this in a single line
ages = np.array([25, 30, 35, 40, 45, 50, 55])
ages

array([25, 30, 35, 40, 45, 50, 55])

Get specific elements - note that in Python, the index starts from 0

In [21]:
ages[0]

25

In [22]:
ages[6]

55

In [23]:
ages[-1] # this is the last element

55

In [24]:
ages[0:4] # goes from index = 0 to 3 (first 4 elements)

array([25, 30, 35, 40])

In [26]:
ages[:4] # goes from beginning to index 3 (same result as above)

array([25, 30, 35, 40])

In [27]:
ages[1:4] # goes from index = 1 to 3 (from 2nd to the 4th elements)

array([30, 35, 40])

In [28]:
ages[1:] # goes from index = 1 to the last element (same result as above)

array([30, 35, 40, 45, 50, 55])

In [29]:
ages[::2] # keeps every 2nd element only

array([25, 35, 45, 55])

In [30]:
ages[::-1] # reverses order of elements

array([55, 50, 45, 40, 35, 30, 25])

Get subset of elements, based on a condition

In [31]:
ages[ages<40]

array([25, 30, 35])

In [32]:
ages[ages<=40]

array([25, 30, 35, 40])

Get no. of elements / length of array

In [33]:
len(ages)

7

Get the mean, minimum, and maximum

In [34]:
ages_mean = np.mean(ages)
ages_mean

40.0

In [35]:
np.min(ages)

25

In [36]:
np.max(ages)

55